### ISSUE TITLE
Would love to help out with some stuff! Do you guys have a roadmap or something I can take a look at?

### ISSUE THREAD

**Issue by michaelryancaputo** [robeio/robe-react-ui#6]

**Comment by serayuzgur** [comment]
@michaelryancaputo Hi, we are now migrating our issues from Trello to Github. It will be completed within 2 days. Thanks.

**Comment by serayuzgur** [comment]
Hello @michaelryancaputo 
As you see we opened a bunch of issues. First of all, you are always welcome to contribute. Since we don't have a contribution document I want to explain it to you, it will be easy to create a document after.
1. Opening issues, please feel free to suggest new components, replacing the old ones or changing the props for easier usage.
2. Testing the UX is important, you can always test the usage of the components and give advice.
3. Pick an issue and create a pull request. Every issue is available for everyone. If it is not clear, request for more information and then we can discuss the issue to explain it better.
4. Clean Code & Clean Coder. Sometimes we get confused by namings of components, props or methods, please do not hesitate to review/refactor our sources and create a pull request.
5. Documentation, it is important we know. Generally, samples and docs are enough for us but not for an outsider. We can call it project blindness, a pair of brand new eyes will be more objective about them.

So, what do you think?

**Comment by michaelryancaputo** [comment]
Hey there, sorry, naturally as soon as I offer to help, work/life gets super busy 😢
